language: shell
os: windows
git:
  depth: false
before_cache:
  - rm -f  %USERPROFILE%/.gradle/caches/modules-2/modules-2.lock
  - rm -rf %USERPROFILE%/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "%USERPROFILE%/.gradle/caches/"
    - "%USERPROFILE%/.gradle/wrapper/"
    - "%USERPROFILE%/.konan"
script:
  - choco install jdk8
  - "./gradlew.bat :desktopBinaries"
before_deploy:
  # TODO: Add this part to the Gradle
  - export VERSION=$(git rev-list --count HEAD)
  - git tag $VERSION
  - move "build/bin/desktop/releaseExecutable/Desktop.exe" "./Desktop-$VERSION.exe"
deploy:
  name: ${VERSION}
  prerelease: true
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_RELEASE_KEY
  file:
    - Desktop-$VERSION.exe
  on:
    repo: Trumeet/Desktop